CarePigeon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/', include('patient.urls', namespace="patient")),
    url(r'^provider/', include('provider.urls', namespace="provider")),
)

patient/urls.py
from django.conf.urls import patterns, url, include
from patient import views
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


dajaxice_autodiscover()

urlpatterns = patterns('',
  # url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^$', 'django.contrib.auth.views.login',{'template_name': 'patient/index.html'}, name='index'),
  url(r'^dashboard$', views.DashboardView.as_view(), name='dashboard'),
  url(r'^detail$', views.PatientDetailView.as_view(), name='detail'),
  url(r'^survey/(?P<survey_token>\d+)$', views.SurveyView.as_view(), name='survey'),
  url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
  # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
  # url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
  # url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
  # url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'patient/dashboard.html'}, name = 'login'),
  url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/patient/'}, name = 'logout'),
  url(r'^ajax$', views.get_pagination_page, name = 'ajax'),
)

urlpatterns += staticfiles_urlpatterns()

provider/urls.py
from django.conf.urls import patterns, url

from provider import views

urlpatterns = patterns('',
  # url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^$', 'django.contrib.auth.views.login',{'template_name': 'provider/index.html'}, name='index'),
  url(r'^dashboard$', views.DashboardView.as_view(), name='dashboard'),
  url(r'^exportfitbitfile$', views.exportfitbitfile, name='exportfitbitfile'),
  url(r'^exportPSfile$', views.exportPSfile, name='exportPSfile'),
  url(r'^exportSurveyResponseFile$', views.exportSurveyResponseFile, name='exportSurveyResponseFile'),
  url(r'^education$', views.EducationView.as_view(), name='education'),
  url(r'^managesurvey$', views.ManageSurveyView.as_view(), name='manageSurvey'),
  url(r'^managepatient$', views.ManagePatientView.as_view(), name='managePatient'),
  url(r'^addeditpatient/(?P<mode>\w+)/(?P<pat_id>\d+)$', views.AddEditPatientView.as_view(), name='addEditPatient'),


  # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
  # url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
  # url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
  # url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'patient/dashboard.html'}, name = 'login'),
  url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/provider/'}, name = 'logout'),
)

provider/models.py
from django.db import models
from jsonfield import JSONField
from patient.models import PatientProfile
from django.contrib.auth.models import User
from datetime import datetime  

# Create your models here.


class ProviderProfile(models.Model):
  def __unicode__(self):
    return u'%s %s %s' % (self.first_name, self.middle_name, self.last_name)

  provider_id = models.AutoField(primary_key=True)
  first_name = models.CharField(max_length=200)
  middle_name = models.CharField(max_length=200)
  last_name = models.CharField(max_length=200)
  title = models.CharField(max_length=200)
  practice = models.CharField(max_length=200)
  imgsrc = models.CharField(max_length=500)
  user = models.ForeignKey(User, unique=True)

class ProviderProfileManager(models.Manager):
  def create_provider(self, first_name, middle_name, last_name, title, practice, imgsrc):
      provider = self.create(first_name = first_name, middle_name = middle_name, last_name = last_name, title = title, practice = practice, imgsrc = imgsrc)
      # do something with the patient
      return provider
  def get_provider_by_user(self, user):
      return self.objects.get(user = user)
      # objects.get(pk=1)



class ProviderPatientLookup(models.Model):
  def __unicode__(self):
    return u'%s %s' % (self.patient_id, self.provider_id)
  patient_id = models.ForeignKey(PatientProfile)
  provider_id = models.ForeignKey(ProviderProfile)
  # provider_id = models.CharField(max_length=200)

class Clinlib(models.Model):
  def __unicode__(self):
    return u'%s %s %s' % (self.first_name, self.middle_name, self.last_name)

  clinlib_id = models.AutoField(primary_key=True)
  title = models.CharField(max_length=500)
  desc = models.CharField(max_length=8000)
  is_youtube = models.BooleanField(default = False)
  uri = models.CharField(max_length=1000)

class ClinlibManager(models.Manager):
  def create_content(self, title, desc, uri):
    is_youtube = False
    if 'youtube.com' in uri:
      is_youtube = True
    content = self.create(title = title, desc = desc , is_youtube = is_youtube, uri = uri )
    return content


class ClinLibPatientLookup(models.Model):
  def __unicode__(self):
    return u'%s %s' % (self.patient_id, self.clinlib_id)
  patient_id = models.ForeignKey(PatientProfile)
  clinlib_id = models.ForeignKey(Clinlib)

class SurveyLib(models.Model):
  def __unicode__(self):
    return u'%s' % (self.title)

  survey_id = models.AutoField(primary_key=True)
  title = models.CharField(max_length=200)
  surevy_structure = JSONField('Survey Structure JSON')

class PatientSurveyLookup(models.Model):
  def __unicode__(self):
    return u'%s %s' % (self.patient_id, self.survey_id)


  patient_id = models.ForeignKey(PatientProfile)
  survey_id = models.ForeignKey(SurveyLib)


class ProviderSurveyLookup(models.Model):
  def __unicode__(self):
    return u'%s %s' % (self.patient_id, self.survey_id)


  daily = 'D'
  weekly = 'W'
  monthly = 'M'

  reminder_frequency_choices = (
    (daily, 'Daily'),
    (weekly, 'Weekly'),
    (monthly, 'Monthly')
    )

  provider_id = models.ForeignKey(ProviderProfile)
  survey_id = models.ForeignKey(SurveyLib)
  reminder_frequency = models.CharField(max_length=2, choices = reminder_frequency_choices, default = monthly)


class PatientSurveyResponse(models.Model):
  def __unicode__(self):
    return u'%s %s' % (self.patient_id, self.response_date)

  patient_id = models.ForeignKey(PatientProfile)
  survey_id = models.ForeignKey(SurveyLib)
  response_date = models.DateTimeField('Response Date', default=datetime.now)
  response = JSONField('Survey Response JSON')

# class PatientSurveyResponseManager(models.Manager):
#   def answer_survey(self, patient_id, survey_id, response):
#     answer = self.create(patient_id, survey_id, response)
#     return answer

provider/forms.py
from django.forms import ModelForm
from django import forms
from provider.models import *

class ClinlibForm(ModelForm):
  title = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter a title...'}))


  class Meta:
    model = Clinlib
    fields = ['title', 'desc', 'uri']

provider/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views import generic
from django.utils import timezone
from vanilla import CreateView, ListView, TemplateView
from functools import partial
from django.template import loader, Context
import plotlyChart as pc
import fitbitAPI as fb
import csv, os, json


# define decorators
from forms import ClinlibForm

from provider.models import *
from patient.views import SurveyView

def logged_in_and_in_group(user):
  r = False
  if user.is_authenticated():
    # group that user needs to be in
    if user.groups.filter(name='providerGroup').exists():
      r = True
  return r

class GroupRequiredMixin(object): 
  # path to be redirected when user is not logged in yet
  login_url = '/provider/'
  
  @method_decorator(user_passes_test(logged_in_and_in_group, login_url=login_url))
  # @method_decorator(user_passes_test(lambda u: u.is_superuser))
  def dispatch(self, *args, **kwargs):
    return super(GroupRequiredMixin, self).dispatch(*args, **kwargs)


class DashboardView(GroupRequiredMixin, generic.View):
  """DashboardView is the first view after login the provider sees"""
  # login_url = '/patient/'
  provider_list = [
    {'name': 'doctor sam', 'title': 'Othropedics','practice': 'Hospital for Special Surgery','has_warning': True},
    {'name': 'doctor pam', 'title': 'Geriatric','practice': 'Cornell Weill Hospital', 'has_warning': False}
  ]

  patient_list = [
     {'id':'123', 'name': 'John Doe', 'firstname': 'John', 'middlename': '','lastname':'Doe'},
     {'id':'4567', 'name': 'Jane Doe', 'firstname': 'Jane', 'middlename': '','lastname':'Doe'}

  ]






  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    user = request.user
    # user = ProviderProfile.get_provider_by_user(user)
    # user = ProviderProfile.objects.get(user = uid )

    pc.plotGraph()

    # if request.GET.__getitem__('exportcsv'):
    #   # render the file request
    #   self.exportfile(request)
    # genrate file
    

    return render(request,'provider/dashboard.html', 
      {"provider_list": self.provider_list,
        "patient_list": self.patient_list,
        "user": user
      } 
      )

def exportPSfile(request):
  # Create the HttpResponse object with the appropriate CSV header.

  # path_to_file = os.path.realpath("/Users/ahau/CarePigeon/provider/static/mHealth pilot data - 20150313.xlsx")
  path_to_file = os.path.realpath("/home/ubuntu/Care-pigeon.com/CarePigeon/provider/static/patient_mhealth.csv")
  f = open(path_to_file, 'r')
  

  # response = HttpResponse(f, content_type='application/vnd.ms-excel')
  # response['Content-Disposition'] = 'attachment; filename="HOOS_Steps.xlsx"'

  response = HttpResponse(f, content_type='text/csv')
  response['Content-Disposition'] = 'attachment; filename="patient_mhealth.csv"'

  f.close()

  return response

def exportfitbitfile(request):
  # Create the HttpResponse object with the appropriate CSV header.
  response = HttpResponse(content_type='text/csv')
  response['Content-Disposition'] = 'attachment; filename="patient_steps.csv"'

  data = fb.getStepsTimeSeries('3m') 

  writer = csv.writer(response)
  for v in data:
    writer.writerow(v)

  return response

def exportSurveyResponseFile(request):
  # Create the HttpResponse object with the appropriate CSV header.
  response = HttpResponse(content_type='text/csv')
  response['Content-Disposition'] = 'attachment; filename="patient_survey_response.csv"'

  headers = [w['question_title'] for w in SurveyView.survey_structure['questions']]
  print headers

  data = PatientSurveyResponse.objects.all()
  for i in data:
    print type(i.response)
    print i.response
    # print i.response['Please indicate how often you performed running']



  writer = csv.writer(response)
  # write headers
  writer.writerow(['Response Date'] + headers)
  for v in data:
    row = []
    row.append(v.response_date)
    for j in headers:
      try:
        row.append(v.response[j])
      except:
        row.append('')
    writer.writerow(row)

  return response


class EducationView(GroupRequiredMixin, generic.View):
  """EducationView is where providers can customize eductaional content show their Clinical Library for patients"""
  # login_url = '/patient/'
  # select client lib * from client lib 


  education_list=[
    {'name': 'Frozen Shoulder', 'desc': 'General information on Frozen Shoulder', 'is_youtube': False, 'link':'http://someAMZNS3link'},
    {'name': 'Frozen Shoulder Video', 'desc': 'Video on Frozen Shoulder', 'is_youtube': True, 'link':'https://www.youtube.com/embed/q0S5EN7-RtI'}


  ]

  def get(self, request):
    # clinlib_form = ClinlibForm
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'provider/education.html', 
      {"education_list": self.education_list,
        "clinlib_form": ClinlibForm
      } 
      )

  def post(self, request):
    # parse request and save content to clinlib
    title = request.POST.get('title', False)
    desc = request.POST.get('desc', False)
    uri = request.POST.get('uri', False)
    # Clinlib.objects.create_content(title = title, desc = desc, uri = uri)


    return render(request,'provider/education.html', 
      {
        "education_list": self.education_list,
        "message" : 'Content: {} is added to your clinical library'.format(title)
        } 
      )

class ManageSurveyView(GroupRequiredMixin, generic.View):
  """EducationView is where providers can customize eductaional content for patients"""
  # login_url = '/patient/'
  survey_list=[
    {'name': 'Pedi-FABS', 'desc': 'Survey for pediatric sports activity and function', 'reminder_sent': 'weekly'},
    {'name': 'WOMAC', 'desc': 'Survey for hip and knee', 'reminder_sent': 'weekly' }

  ]

  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'provider/managesurvey.html', 
      {"survey_list": self.survey_list} 
      )

class ManagePatientView(GroupRequiredMixin, generic.View):
  """PatientView is where providers can manage their patients"""
  # login_url = '/patient/'
  patient_list=[
    {'id':'123','name': 'John Doe'},
    {'id':'456','name': 'Jane Doe'}

  ]

  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'provider/managepatient.html', 
      {"patient_list": self.patient_list} 
      )

class AddEditPatientView(GroupRequiredMixin, generic.View):
  """AddEditPatientView is where providers can add or edit the patient"""
  # login_url = '/patient/'
  patient ={'id':'123', 'name': 'John Doe', 'firstname': 'John', 'middlename': '','lastname':'Doe'}
  patient_assigned_surveys = [{'name':'Pedi-FABS' }]

  patient_assigned_content = [{'name':'Frozen Shoulder' }, {'name':'Frozen Shoulder Video'}]

  education_list=[
    {'name': 'Frozen Shoulder', 'desc': 'General information on Frozen Shoulder', 'is_youtube': False, 'link':'http://someAMZNS3link'},
    {'name': 'Frozen Shoulder Video', 'desc': 'Video on Frozen Shoulder', 'is_youtube': True, 'link':'https://www.youtube.com/embed/q0S5EN7-RtI'}
  ]

  survey_list=[
    {'name': 'Pedi-FABS', 'desc': 'Survey for pediatric sports activity and function', 'reminder_sent': 'weekly'},
    {'name': 'WOMAC', 'desc': 'Survey for hip and knee', 'reminder_sent': 'weekly' }

  ]
  

  def post(self, request, mode, pat_id):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'provider/addeditpatient.html', 
      {
        "patient": self.patient,
        "patient_assigned_surveys": self.patient_assigned_surveys,
        "patient_assigned_content": self.patient_assigned_content,
        "education_list": self.education_list,
        "survey_list": self.survey_list
        }

      )











class ProviderDetailView(GroupRequiredMixin, generic.View):
  """PatientDetailView is the view after patient selects a specific provider"""
  # login_url = '/patient/'
  provider_detail_list ={
    'name': 'doctor sam', 
    'title': 'Othropedics',
    'practice': 'Hospital for Special Surgery',
    'has_warning': True
  }

  survey_token = '123'

  education_list=[
    {'name': 'Frozen Shoulder', 'desc': 'General information on Frozen Shoulder', 'is_youtube': False, 'link':'http://someAMZNS3link'},
    {'name': 'Frozen Shoulder Video', 'desc': 'Video on Frozen Shoulder', 'is_youtube': True, 'link':'https://www.youtube.com/embed/q0S5EN7-RtI'}


  ]

  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'provider/detail.html', 
      {"provider_list": self.provider_detail_list,
        "survey_token": self.survey_token,
        "education_list": self.education_list

        } 
      )

# class SurveyView(GroupRequiredMixin, generic.View):
#   """SurveyView handles loading the survey the patient needs to answer"""
#   survey_token = '123'
#   survey_structure = {
#     'name': 'Pedi-FABS',
#     'questions':[
#       {'question_title':'Please indicate how often you performed running', 
#         'question_id': '1',
#         'question_helper': '(running while playing a sport or jogging) in your healthiest and most active condition in the past month.',
#         'question_type': 'multiple-choice',
#         'question_choices': [{'choice': 'less than one time per month'},
#                               {'choice': 'one time per month'},

provider/templates/provider/dashboard.html
{% extends 'provider/layout.html' %}

{% block customScripts %}

  
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

    <script type="text/javascript">
$(function () {
    $('#highcharts-container').highcharts({
        chart: {
            zoomType: 'xy'
        },
        title: {
            text: 'HOOS_PS and Steps Time Series'
        },
        // subtitle: {
        //     text: 'Source: WorldClimate.com'
        // },
        xAxis: [{
            min: -10,
            max: 76,
            crosshair: true,
            title: {
                text: 'Days since surgery'
            }
        }],
        yAxis: [{ // Primary yAxis
            min: 0,
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            },
            title: {
                text: 'HOOS_PS',
                style: {
                    color: Highcharts.getOptions().colors[1]
                }
            }
        }, { 
            min: 0,
            title: {
                text: 'Steps',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            labels: {
                format: '{value}',
                style: {
                    color: Highcharts.getOptions().colors[0]
                }
            },
            opposite: true
        }],
        tooltip: {
            shared: true
        },
        legend: {
            layout: 'vertical',
            align: 'left',
            x: 120,
            verticalAlign: 'top',
            y: 100,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        series: [{
            name: 'Steps',
            type: 'spline',
            yAxis: 1,
            data: [[-8, 207], [-7, 423], [-6, 1232], [-5, 295], [-4, 467], [-3, 183], [-2, 250], [-1, 311], [0, 61], [1, 2731], [2, 264], [3, 688], [4, 1467], [15, 18], [16, 586], [17, 288], [19, 430], [20, 1942], [21, 1270], [22, 82], [23, 3527], [24, 2747], [25, 2021], [26, 2597], [27, 5443], [28, 5703], [29, 5635], [30, 6602], [31, 923], [32, 30], [33, 7100], [34, 748], [35, 3074], [36, 8248], [37, 5340], [38, 5128], [39, 8676], [40, 4760], [41, 4723], [42, 260], [43, 4979], [44, 5177], [45, 4634], [46, 210], [47, 1004], [48, 91], [49, 1038], [50, 641], [51, 960], [52, 466], [53, 3938], [54, 4784], [55, 3149], [56, 809], [57, 735], [58, 5979], [59, 132], [60, 3673], [61, 952], [62, 7158], [63, 1892], [64, 2594], [65, 9512], [66, 112], [67, 6632], [68, 1027], [69, 1561], [70, 1543], [71, 1338], [72, 5703], [73, 4498], [74, 3045], [75, 2531]],
            tooltip: {
                valueSuffix: ''
            }

        }, {
            name: 'HOOS_PS',
            type: 'spline',
            data: [[-3, 30.4], [4, 8.8], [11, 46.1], [18, 90.8], [25, 90.8], [32, 82.4], [39, 90.8], [53, 100], [60, 100], [74, 100]],
            tooltip: {
                valueSuffix: ''
            }
        }],
        credits : false

    });
});
    </script>


{% endblock customScripts %}

{% block custombody_content %}








<div class="container">

<div class="page-header text-center">
  <img style="width: 100px; height: 100px"src="/static/provider/images/samtaylor.png">
  <h1>Welcome Dr. {{ user.last_name }}</h1>
</div>



<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <div class="list-group">
      <div class="list-group-item active">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for Patient...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div><!-- /input-group -->
      </div>
      {% for item in patient_list %}

      <a class="list-group-item">
       <strong>{{ item.name }}</strong>, patient id: {{ item.id }}
      </a>

      {% endfor %}
      
    </div>
    
  </div><!-- /.col-lg-6 -->
  <div class="col-lg-3"></div>
</div>



<script src="/static/js/highcharts.src.js"></script>
<script src="/static/js/modules/exporting.js"></script>
<div id="highcharts-container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>




<br>
<form method="get" action="{% url 'provider:exportPSfile' %}" >
  <button class="btn btn-lg btn-primary" type="submit">
    Download Data <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
  </button>
</form>
<br>

<div>
    <a href="https://plot.ly/~alan.wc.hau/97/" target="_blank" title="Step Count Time series " style="display: block; text-align: center;"><img src="https://plot.ly/~alan.wc.hau/97.png" alt="Step Count Time series " style="max-width: 100%;"  onerror="this.onerror=null;this.src='https://plot.ly/404.png';" /></a>
    <script data-plotly="alan.wc.hau:97" src="https://plot.ly/embed.js" async></script>
</div>


<form method="get" action="{% url 'provider:exportfitbitfile' %}" >
  <button class="btn btn-lg btn-primary" type="submit">
    Download Step Data <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
  </button>
</form>


<form method="get" action="{% url 'provider:exportSurveyResponseFile' %}" >
  <button class="btn btn-lg btn-primary" type="submit">
    Download Survey Data <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
  </button>
</form>



<br>

</div>
{% endblock custombody_content %}

provider/templates/provider/index.html
{% extends 'provider/layout.html' %}
{% load staticfiles %}

{% block customScripts %}

<style type="text/css">
html { 
  background: url("{% static "provider/images/loopingwillow.gif" %}") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

body {


  padding-bottom: 125px;
  background-color: transparent;
}
    .vertical-align {
    /* display: table-cell;*/
   text-align: center;
   vertical-align: middle;
}

.footer {
  visibility: hidden;
}




  </style>


{% endblock customScripts %}

{% block custombody_content %}





  <div class="container" style="padding: 100px">
    <div class="row">
    
    <div class="col-lg-4"></div>
    <div class="col-lg-4">

      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Provider Portal Login</strong>
        </div>
        <div class="panel-body">
          <!-- <form method="post" action="index.html">
            <p><input type="text" name="login" value="" placeholder="Username or Email"></p>
            <p><input type="password" name="password" value="" placeholder="Password"></p>
            <p class="remember_me">
              <label>
                <input type="checkbox" name="remember_me" id="remember_me">
                Remember me on this computer
              </label>
            </p>
            <input class="btn btn-success" type="submit" name="commit" value="Login">
          </form> -->
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
          <form method="post" action="{% url 'provider:index' %}">
          {% csrf_token %}


            <!-- <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div> -->

            

            <div class="form-group">
              <label for="id_username">Username:</label>
              <input class="form-control" id="id_username" maxlength="254" name="username" type="text">
              <label for="id_password">Password:</label>
              <input class="form-control" id="id_password" name="password" type="password">
            </div>



            <input type="submit" class="btn btn-primary" value="login" />
            {% if next %}
              <input type="hidden" name="next" value="{{ next }}" />
            {% else %}
              <input type="hidden" name="next" value="{% url 'provider:dashboard' %}" />
            {% endif %}

            <!-- <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button> -->
          </form>

          <br>
          
          <a href="#">Forgot your password?</a>

          
          
        </div>
      </div>

    </div>
    <div class="col-lg-4"></div>


    </div>
   
  </div>


{% endblock custombody_content %}

provider/templates/provider/layout.html
{% block djfrontend_twbs_css %}
    <!-- <link href="/static/css/bootstrap.css" rel="stylesheet"> -->
    <title>CarePigeon-Provider Site</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

    
    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 50px;
        /*padding-bottom: 0px;*/
      }


      
    </style>



    {% block customScripts %}
    {% endblock customScripts %}
{% endblock djfrontend_twbs_css %}


{% block body_content %}

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CP Outcomes</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'provider:dashboard'%}">Provider Dashboard</a></li>
            <li><a href="{% url 'provider:education'%}">Clinical Library</a></li>
            <li><a href="{% url 'provider:manageSurvey'%}">Surveys</a></li>
            <li><a href="{% url 'provider:managePatient'%}">Patients</a></li>
            <li><a href="/About">About</a></li>
          
          </ul>

          {% if user.is_authenticated %}
          <form class="navbar-form navbar-right" method="get" action="/provider/logout" style="margin: 0px;">
            <div class="form-group">
              <p class="navbar-text">Welcome, {{ user.first_name }} {{ user.last_name }}</p> 
            </div>
            <button type="submit" class="btn btn-success">Logout</button>
          </form>
          {% endif %}

        </div>
      </div>
    </div>




{% block custombody_content %}
{% endblock custombody_content %}

    <div class="container">



<footer class="footer">
        
        <div class="container">
        <hr>
          <p>&copy; Care Pigeon 2014</p>
        </div>
      </footer>



  {% endblock body_content %}


        

provider/templates/provider/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>