CarePigeon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^patient/', include('patient.urls', namespace="patient")),
    url(r'^provider/', include('provider.urls', namespace="provider")),
)

patient/urls.py
from django.conf.urls import patterns, url, include
from patient import views
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


dajaxice_autodiscover()

urlpatterns = patterns('',
  # url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^$', 'django.contrib.auth.views.login',{'template_name': 'patient/index.html'}, name='index'),
  url(r'^dashboard$', views.DashboardView.as_view(), name='dashboard'),
  url(r'^detail$', views.PatientDetailView.as_view(), name='detail'),
  url(r'^survey/(?P<survey_token>\d+)$', views.SurveyView.as_view(), name='survey'),
  url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
  # url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
  # url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
  # url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
  # url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'patient/dashboard.html'}, name = 'login'),
  url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/patient/'}, name = 'logout'),
  url(r'^ajax$', views.get_pagination_page, name = 'ajax'),
)

urlpatterns += staticfiles_urlpatterns()

patient/models.py
from django.db import models
from jsonfield import JSONField
from django.contrib.auth.models import User
# from provider.models import ProviderProfile, ClinLib

class PatientProfile(models.Model):
  def __unicode__(self):
    return u'%s %s %s' % (self.first_name, self.middle_name, self.last_name)

  patient_id = models.AutoField(primary_key=True)
  first_name = models.CharField(max_length=200)
  middle_name = models.CharField(max_length=200)
  last_name = models.CharField(max_length=200)
  date_of_birth = models.DateTimeField('Date of Birth')
  date_of_surgery = models.DateTimeField('Date of Surgery')
  user = models.ForeignKey(User, unique=True)
  # settings.AUTH_USER_MODEL
  email = models.EmailField(max_length=254, default= 'patient@noemail.com')

class PatientProfileManager(models.Manager):
    def create_patient(self, first_name, middle_name, last_name, date_of_birth, date_of_surgery):
        patient = self.create(first_name = first_name, middle_name = middle_name, last_name = last_name, date_of_birth = date_of_birth, date_of_surgery = date_of_surgery)
        # do something with the patient
        return patient

# class BookManager(models.Manager):
#     def create_book(self, title):
#         book = self.create(title=title)
#         # do something with the book
#         return book

# class Book(models.Model):
#     title = models.CharField(max_length=100)

#     objects = BookManager()

# book = Book.objects.create_book("Pride and Prejudice")

patient/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from vanilla import CreateView, ListView, TemplateView
from functools import partial
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger

# define decorators
from provider.models import *

def logged_in_and_in_group(user):
  r = False
  if user.is_authenticated():
    # group that user needs to be in
    if user.groups.filter(name='patientGroup').exists():
      r = True
  return r

class GroupRequiredMixin(object): 
  # path to be redirected when user is not logged in yet
  login_url = '/patient/'
  
  @method_decorator(user_passes_test(logged_in_and_in_group, login_url=login_url))
  # @method_decorator(user_passes_test(lambda u: u.is_superuser))
  def dispatch(self, *args, **kwargs):
    return super(GroupRequiredMixin, self).dispatch(*args, **kwargs)


class DashboardView(GroupRequiredMixin, generic.View):
  """DashboardView is the first view after login the patient sees"""
  # login_url = '/patient/'
  provider_list = [
    {'name': 'Dr. Taylor', 'imgsrc': '/static/patient/images/samtaylor.png', 'title': 'Orthopaedics, Sports Medicine & Shoulder','practice': 'Hospital for Special Surgery', 'is_flagged': True },
    {'name': 'Dr. O\'Brien', 'imgsrc': '/static/patient/images/stephenobrien.png', 'title': 'Orthopaedics, Sports Medicine & Shoulder','practice': 'Hospital for Special Surgery', 'is_flagged': False}
  ]

  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'patient/dashboard.html', 
      {"provider_list": self.provider_list} 
      )

class PatientDetailView(GroupRequiredMixin, generic.View):
  """PatientDetailView is the view after patient selects a specific provider"""
  # login_url = '/patient/'
  provider_detail_list ={
    'name': 'Dr. Taylor', 
    'title': 'Orthopaedics, Sports Medicine & Shoulder',
    'practice': 'Hospital for Special Surgery',
    # 'has_warning': True,
    'imgsrc': '/static/patient/images/samtaylor.png'
  }

  survey_token = '123'

  education_list=[
    {'name': 'Frozen Shoulder', 'desc': 'General information on Frozen Shoulder', 'is_read': False, 'is_youtube': False, 'link':'http://orthoinfo.aaos.org/PDFs/A00071.pdf'},
    {'name': 'Frozen Shoulder Video', 'desc': 'Video on Frozen Shoulder', 'is_read':True,'is_youtube': True, 'link':'https://www.youtube.com/embed/vJ-hm8bzOsk'}


  ]


  def get(self, request):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))

    return render(request,'patient/detail.html', 
      {"provider_list": self.provider_detail_list,
        "survey_token": self.survey_token,
        "education_list": self.education_list

        } 
      )

class SurveyView(GroupRequiredMixin, generic.View):
  """SurveyView handles loading the survey the patient needs to answer"""
  survey_token = '123'
  # survey_structure = {
  #   'name': 'Pedi-FABS',
  #   'questions':[
  #     {'question_title':'Please indicate how often you performed running', 
  #       'question_id': '1',
  #       'question_helper': '(running while playing a sport or jogging) in your healthiest and most active condition in the past month.',
  #       'question_type': 'multiple-choice',
  #       'question_choices': [{'choice': 'less than one time per month'},
  #                             {'choice': 'one time per month'},
  #                             {'choice': 'one time per week'},
  #                             {'choice': '2-3 times per week'},
  #                             {'choice': 'more than 4 times per week'}
  #                           ]
  #       },
  #     {'question_title':'Please indicate how often you performed cutting', 
  #       'question_id': '2',
  #       'question_helper': '(quickly changing directions while running) in your healthiest and most active condition in the past month.',
  #       'question_type': 'multiple-choice',
  #       'question_choices': [{'choice': 'less than one time per month'},
  #                             {'choice': 'one time per month'},
  #                             {'choice': 'one time per week'},
  #                             {'choice': '2-3 times per week'},
  #                             {'choice': 'more than 4 times per week'}
  #                           ]
  #       },
  #   ]
  # }

  survey_structure = {
    'name': 'KOOS Jr',
    'questions':[
      {'question_title':'In the last week, how severe is your knee stiffness after first wakening in the morning?', 
        'question_id': '1',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'What amount of knee pain have you experienced the last week twisting/pivoting on your knee?', 
        'question_id': '2',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'What amount of knee pain have you experienced the last week straightening your knee fully?', 
        'question_id': '3',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'What amount of knee pain have you experienced the last week going up or down stairs?', 
        'question_id': '4',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'What amount of knee pain have you experienced the last week standing upright?', 
        'question_id': '5',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'Please indicate the degree of difficulty you have experienced in the last week due to your knee in rising from sitting:', 
        'question_id': '6',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'Please indicate the degree of difficulty you have experienced in the last week due to your knee in bending to floor/picking up an object:', 
        'question_id': '7',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        },
      {'question_title':'Please indicate the degree of difficulty you have experienced in the last week due to your knee going shopping:', 
        'question_id': '8',
        'question_helper': '',
        'question_type': 'multiple-choice',
        'question_choices': [{'choice': 'none'},
                              {'choice': 'mild'},
                              {'choice': 'moderate'},
                              {'choice': 'severe'},
                              {'choice': 'extreme'}
                            ]
        }
    ]
  }

  def get(self, request, survey_token):
    # return render_to_response('patient/dashboard.html', context_instance = RequestContext(request))
    return render(request,'patient/survey.html', 
      {"survey_token": self.survey_token,
        "survey_structure": self.survey_structure,
        } 
      )

  def post(self, request, survey_token):
    # print request.POST['Please indicate how often you performed running']
    # print request
    # save results back to DB

    patient_id = PatientProfile.objects.get(user = request.user)
    survey_id = SurveyLib.objects.get(title = 'KoosJr')


    p = PatientSurveyResponse.objects.create(patient_id = patient_id, survey_id = survey_id, response = request.POST)


    return redirect('/patient/detail?s=1' 
      )



def get_pagination_page(page=1):
    items = range(0, 100)
    paginator = Paginator(items, 10)
    try:
        page = int(1)
    except ValueError:

patient/templates/patient/ajax.html
{% for i in items.object_list %}
    {{ i }}<br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if items.has_previous %}
            <a href="#" onclick="pagination(Dajax.process,{'p':{{ items.previous_page_number }}})">previous</a>
        {% endif %}

        <span class="current">
            Page {{ items.number }} of {{ items.paginator.num_pages }}.
        </span>

        {% if items.has_next %}
            <a href="#" onclick="pagination(Dajax.process,{'p':{{ items.next_page_number }}})">next</a>
        {% endif %}
    </span>
</div>

patient/templates/patient/dashboard.html
{% extends 'patient/layout.html' %}

{% block customScripts %}


{% endblock customScripts %}

{% block custombody_content %}

<div class="container">
<div class="page-header">
  <h1>Welcome {{ user.username }}</h1>
</div>

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="list-group">
{% for provider in provider_list %}

      {% if provider.is_flagged %}
      <a href="{% url 'patient:detail' %}" class="list-group-item list-group-item-warning">
      {% else %}
      <a href="{% url 'patient:detail' %}" class="list-group-item">
      {% endif %}  

          <div class="row">
            <div class="col-lg-2">
              <img style="width: 100px; height: 100px"src="{{ provider.imgsrc }}">
            </div>
            <div class="col-lg-8">
              
                <h4 >{{provider.name}}</h4>
              <p class="list-group-item-text">Title: {{provider.title}}</p>
              <p class="list-group-item-text">Practice: {{provider.practice}}</p>
              <!-- <p class="list-group-item-text">Flag?: {{provider.has_warning}}</p> -->
            </div>

            {% if provider.is_flagged %}
            <div class="col-lg-2" align="center">
              <span class="glyphicon glyphicon-alert btn-lg" style="font-size: 50px;" aria-hidden="true"></span>
            </div>
            {% endif %}
              
          
          </div>
        
    
      </a>




{% empty %}
    <a>Sorry, no physician has registered with you yet.</a>
{% endfor %}
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>


</div>
{% endblock custombody_content %}

patient/templates/patient/detail.html
{% extends 'patient/layout.html' %}

{% block customScripts %}
  <style type="text/css">
  .auto-resizable-iframe {
  /*max-width: 420px;*/
  max-width: 80%;
  margin: 0px auto;
}

.auto-resizable-iframe > div {
  position: relative;
  padding-bottom: 75%;
  height: 0px;
}

.auto-resizable-iframe iframe {
  position: absolute;
  top: 0px;
  left: 0px;
  width: 100%;
  height: 100%;
}
  </style>

{% endblock customScripts %}

{% block custombody_content %}

<div class="container">
  <div class="page-header">
    <div class="row">
      <div class="col-lg-2">
        <img src="{{ provider_list.imgsrc }}">
      </div>
      <div class="col-lg-10">
        <h1>{{provider_list.name}}'s page</h1>
        <h3>{{provider_list.title}}, {{provider_list.practice}}</h3>
      </div>  
    </div>    
  </div>


  <div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="list-group">
      <a href="{% url 'patient:survey' survey_token %}">
        <div class="alert alert-warning">
          <div class="row">
            
          
            <div class="col-lg-10" align='center'>
              <h3>You have an unanswered survery: KOOS jr, click to take it now!</h3>
            </div>

            <div class="col-lg-2" align="center">
              <span class="glyphicon glyphicon-alert btn-lg" style="font-size: 50px;" aria-hidden="true"></span>
            </div>
          </div>
        </div>
      </a>
    </div>

    {% ifequal request.GET.s '1'  %}
    <div class="row">
      <div class="alert alert-success text-center">
        thanks for answering!
      </div>
    </div>
    {% endifequal %}
  </div>
  <div class="col-sm-2"></div>
  </div>

    <div class="row">
    <div class="col-sm-8">
      <div class="well">
        
        <div class="row">
          <div class="col-lg-12 text-center">
            <h1>Recommendations by {{ provider_list.name }} </h1>
            <br>
          </div>
        </div>
        
        <ul class="list-group">
        {% for item in education_list %}
          {% if item.is_read %}
            <a class="list-group-item" href="{{item.link}}">
          {% else %}
            <a class="list-group-item list-group-item-warning" href="{{item.link}}">
                <span class="badge">New</span>
          {% endif %}

              
                <h4 class="list-group-item-heading">{{item.name}}</h4>
                <p class="list-group-item-text">description: {{item.desc}}</p>
                <p class="list-group-item-text">link: {{item.link}}</p>
               <!--  <p>button for downlaod</p> -->
                {% if item.is_youtube %}
                  <br>
                  <div class="auto-resizable-iframe">
                    <div>
                      <iframe frameborder="0" allowfullscreen="" src="{{ item.link }}"></iframe>
                    </div>  
                  </div>
                {% endif %}
                <!-- <iframe width="854" height="510" src="https://www.youtube.com/embed/q0S5EN7-RtI" frameborder="0" allowfullscreen></iframe> -->
              </a>

        {% empty %}
            <li>Sorry, your doctor has not assigned any information for you yet.</li>
        {% endfor %}
        </ul>
      </div>
    </div>

    
    <div class="col-sm-4">
      <div class="well">
          <div class="row">
          <div class="col-sm-12 text-center">
            <h1>Personal Notes</h1>
            <br>
          </div>
        </div>
          

             <textarea style='margin-bottom: 20px'class="form-control" rows="10" placeholder="Jot down personal questions for your provider here so you can ask them on your next visit..." required></textarea>

             
          
         

 
              <button type="submit" class="btn btn-lg btn-primary btn-block">Save</button>

              <br>
              <p>If you think you may have a medical emergency, call your doctor or 911 immediately. CarePigeon does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on the Site. Reliance on any information provided by CarePigeon, CarePigeon employees, others appearing on the Site at the invitation of CarePigeon, or other visitors to the Site is solely at your own risk.</p>



      </div>
    </div>
      

  </div>



</div>

{% endblock custombody_content %}

patient/templates/patient/index.html
{% extends 'patient/layout.html' %}
{% load staticfiles %}

{% block customScripts %}

<style type="text/css">
html { 
  background: url("{% static "patient/images/plants_subtle_sunset_600.gif" %}") no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

body {

  padding-bottom: 125px;
  background-color: transparent;
}
    .vertical-align {
    /* display: table-cell;*/
   text-align: center;
   vertical-align: middle;
}

.footer {
  visibility: hidden;
}


  </style>


{% endblock customScripts %}

{% block custombody_content %}





  <div class="container" style="padding: 100px">
    <div class="row">
    
    <div class="col-lg-4"></div>
    <div class="col-lg-4">

      <div class="panel panel-default">
        <div class="panel-heading">
          <strong>Patient Portal Login</strong>
        </div>
        <div class="panel-body">
          <!-- <form method="post" action="index.html">
            <p><input type="text" name="login" value="" placeholder="Username or Email"></p>
            <p><input type="password" name="password" value="" placeholder="Password"></p>
            <p class="remember_me">
              <label>
                <input type="checkbox" name="remember_me" id="remember_me">
                Remember me on this computer
              </label>
            </p>
            <input class="btn btn-success" type="submit" name="commit" value="Login">
          </form> -->
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
          <form method="post" action="{% url 'patient:index' %}">
          {% csrf_token %}


            <!-- <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div> -->

            

            <div class="form-group">
              <label for="id_username">Username:</label>
              <input class="form-control" id="id_username" maxlength="254" name="username" type="text">
              <label for="id_password">Password:</label>
              <input class="form-control" id="id_password" name="password" type="password">
            </div>



            <input type="submit" class="btn btn-primary" value="login" />
            {% if next %}
              <input type="hidden" name="next" value="{{ next }}" />
            {% else %}
              <input type="hidden" name="next" value="{% url 'patient:dashboard' %}" />
            {% endif %}

            <!-- <button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button> -->
          </form>

          <br>
          
          <a href="#">Forgot your password?</a>
          
          
        </div>
      </div>

    </div>
    <div class="col-lg-4"></div>


    </div>
   
  </div>


{% endblock custombody_content %}

patient/templates/patient/layout.html
{% extends 'djfrontend/skeleton.html' %}

{% block djfrontend_twbs_css %}
    <!-- <link href="/static/css/bootstrap.css" rel="stylesheet"> -->
    <title>CarePigeon-Patient Site</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
    
    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 50px;
        /*padding-bottom: 0px;*/
      }


      
    </style>

    {% block customScripts %}
    {% endblock customScripts %}
{% endblock djfrontend_twbs_css %}


{% block body_content %}

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CP Outcomes</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'patient:dashboard'%}">Patient Dashboard</a></li>
            <li><a href="/About">About</a></li>
          


<!--             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->

          </ul>

          {% if user.is_authenticated %}
          <form class="navbar-form navbar-right" method="get" action="/patient/logout" style="margin: 0px;">
            <div class="form-group">
              <p class="navbar-text">Welcome, {{ user.first_name }} {{ user.last_name }}</p> 
            </div>
            <button type="submit" class="btn btn-success">Logout</button>
          </form>
          {% endif %}
          <!-- <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form> -->
        </div>
      </div>
    </div>



    <!-- Main jumbotron for a primary marketing message or call to action -->
<!--     <div class="jumbotron">
      <div class="container">
        <h1>Welcome to django-skeleton</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="http://getbootstrap.com/">Learn more &raquo;</a></p>
      </div>
    </div> -->

{% block custombody_content %}
{% endblock custombody_content %}



      

<footer class="footer">
        
        <div class="container">
        <hr>
          <p>&copy; Care Pigeon 2015</p>
        </div>
      </footer>



  {% endblock body_content %}


        

patient/templates/patient/listgroup.html
<div class="pagination">
    <span class="step-links text-right">
        {% if education_list.has_previous %}
            <a href="?page={{ education_list.previous_page_number }}">previous</a>
        {% endif %}
        <div>
        <span class="current text-center">
            <p>Page {{ education_list.number }} of {{ education_list.paginator.num_pages }}.</p>
        </span>
      </div>

        {% if education_list.has_next %}
            <a href="?page={{ education_list.next_page_number }}"> <strong>Next module </strong></a>
        {% endif %}
    </span>
</div>

patient/templates/patient/survey.html
{% extends 'patient/layout.html' %}

{% block customScripts %}


{% endblock customScripts %}

{% block custombody_content %}

<form action="{% url 'patient:survey' survey_token %}" method="post">
{% csrf_token %}
  <div class="container">
    <h1>{{ survey_structure.name }}</h1>
    <ul class="list-group">
      {% for question in survey_structure.questions %}
        <li class="list-group-item">
          <h4>{{ question.question_title }}</h4>
          <p>{{ question.question_helper }}</p>
          {% if question.question_type == 'multiple-choice' %}
            {% for item in question.question_choices %}
              <div class="radio">
                <label><input type="radio" name="{{ question.question_title }}" value="{{ item.choice }}">{{ item.choice }}</label>
              </div>
            {% endfor %}
          {% endif %}

        </li>

      {% endfor %}
    </ul>



    

  <button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button>

  </div>
</form>
{% endblock custombody_content %}